swagger: "2.0"
info:
    title: "Google Cloud POC getService API"
    version: "1.0"
    license:
      name: MIT
basePath: /v1.0
schemes:
  - http
produces:
  - application/json
paths:
  /list:
    get:
      responses:
        "200":
          description: "Get a list of all items in the DB"
          schema:
            type: array
            items:
              type: string
