#Test file setting the various environment variables
GCPOC_DB_HOST='172.16.36.129'
GCPOC_DB_USER='GCPOC'
GCPOC_DB_PASSWORD='GCPOCPassword'
GCPOC_DB_DATABASE='GCPOC'
export GCPOC_DB_HOST GCPOC_DB_USER GCPOC_DB_PASSWORD GCPOC_DB_DATABASE
