CREATE DATABASE GCPOC;
GRANT ALL PRIVILEGES ON GCPOC.* TO 'GCPOC'@'%' IDENTIFIED BY 'GCPOCPassword';
USE testdb;
CREATE TABLE gcpoc (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, instring TEXT);
INSERT INTO gcpoc(instring) VALUES ('Seed 1'),('Seed 2'),('Seed 3');
